SAMYCoreConfig:
     AppURI: "AppURItest"
     AppName: "AppNameTest"
     Server:
        Port: 4840
        Encryption: false
        Anonymous: true
        CertificatesPath: ""
     Logging:
        Level:
           App: "info"
           OPCUA: "error"
        Path: "logs"
     ConfigFiles:
        SkillsFile: "/usr/src/samy/SAMYCore/Skills" 
        RobotsFile: "/usr/src/samy/SAMYCore/configFiles_examples/RobotsConfiguration.yaml"
        InformationSourcesFile: "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/SAMYCore/configFiles_examples/InformationSources.yaml"
        DataBaseFile: "/usr/src/samy/SAMYCore/configFiles_examples/DataBaseFile.yaml"
