Robots:
  - Robot:
      Name: RobotUR5
      ID: 12344
      Address: "opc.tcp://localhost:4840"
      OPCUARoboticsFile: RobotUR5.xml
      Skills:
         - MoveToWithSpeed
         - SetEndEffectorSkill
         - PickSkill
         - PickAndPlaceSkill
