function(include_SAMYCore_Library_headers)
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/build/src_generated" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/usr/include/python3.8" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/OPCUA_Models" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/ThirdParty" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/ThirdParty/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/ThirdParty/spdlog" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/Core/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/Helpers/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/InformationSource/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/Logging/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/OPCUA_Server/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/Parsers/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/Reflection/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/SAMYCoreConfig/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/SAMYCoreInterfaceGenerator/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/SAMYRobot/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/SAMYSkill/SkillsScripting/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/SAMYSkill/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/Scripting/CPP/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/Scripting/Python/include" )
	target_include_directories( ${LIBRARY_NAME} PUBLIC "/home/jbg/Desktop/PUBLISHING_REPOS_PREPARATION/F/SAMYCore/src/Scripting/include" )
endfunction()