name: Linux Build

on: push #[push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y -qq build-essential cmake git libyaml-cpp-dev libspdlog-dev
    - name: "Checkout open62541"
      uses: actions/checkout@v2
      with:
        repository: open62541/open62541
        path: open62541
        ref: v1.2.4
        submodules: true
    - name: "Build open63541"
      uses: ./.github/actions/build_linux
      with:
        build-type: build_open62541
    - name: "Checkout Catch2"
      uses: actions/checkout@v2
      with:
        repository: catchorg/Catch2
        path: Catch2
        ref: v2.13.4
        submodules: true
    - name: "Build Catch2"
      uses: ./.github/actions/build_linux
      with:
        build-type: build_catch2
    - name: "Go back to this repository"
      run: |
        cd ${{ github.workspace }}
    - name: "Build SAMYCore"
      uses: ./.github/actions/build_linux
      with:
        build-type: build_release
    - name: "Upload the testsServer binary"
      uses: actions/upload-artifact@master
      with:
           name: testsServer
           path: build/testsServer
    - name: "Upload the testsClient binary"
      uses: actions/upload-artifact@master
      with:
           name: testsClient
           path: build/testsClient
  test:
      runs-on: ubuntu-20.04
      needs: [build]
      steps:
      - run: |
             sudo apt-get update
      - run: |
             mkdir -p binaries
      - name: "Download the testsServer binary"
        uses: actions/download-artifact@master
        with:
            name: testsServer
            path: binaries
      - name: "Download the testsClient binary"
        uses: actions/download-artifact@master
        with:
            name: testsClient
            path: binaries
      - run: |
             cd binaries
             sudo chmod +x testsServer
             sudo chmod +x testsClient
             ./testsServer [ServerTest] &
             sleep 5
             ./testsClient
             cd ..
